# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    concat: "puppetlabs/concat"
    postgresql: "puppetlabs/postgresql"
    redis: "puppet/redis"
    stdlib: "puppetlabs/stdlib"
    augeas_core: "puppetlabs/augeas_core"
